name: Release
on:
  push:
    branches: ["master"]
    tags: ["*"]
jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: openjdk@1.11
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Scala cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.OS }}-scala-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
          restore-keys: |
            ${{ runner.OS }}-scala-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.OS }}-scala-cache-${{ matrix.scala }}-
            ${{ runner.OS }}-scala-cache-
      - name: Pull postgres image
        run: docker ps && docker pull postgres:12.3-alpine
      - uses: olafurpg/setup-gpg@v2
      - name: Setup Jekyll
        run: gem install jekyll -v 4.1.1
      - name: Publish ${{ github.ref }}
        run: sbt test ci-release publishMicrosite
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
